language: java
jdk:
  - oraclejdk8
  
services:
  - postgresql
  
addons:
  postgresql: "9.4"
  
env:
- SPRING_DATASOURCE_USERNAME=postgres SPRING_DATASOURCE_PASSWORD=

before_script:
  - psql -c 'create database spotko_dev;' -U postgres